DROP TABLE IF EXISTS OG_USER;
CREATE TABLE OG_USER (
    USER_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    PHONE VARCHAR(20) NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD LONGTEXT NOT NULL,
    ACTIVE INT NOT NULL DEFAULT 1,
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
